force-app/main/default/objects/Product2/fields/colorTheme__c.field-meta.xml
<CustomField>
    <fullName>colorTheme__c</fullName>
    <defaultValue>&apos;Spectacular Sunset&apos;</defaultValue>
    <label>Color Theme</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Beautiful Blue</fullName>
            </value>
            <value>
                <fullName>Glorious Green</fullName>
            </value>
            <value>
                <fullName>Pretty Pink</fullName>
            </value>
            <value>
                <fullName>Pleasant Purple</fullName>
            </value>
            <value>
                <fullName>Wonderful White</fullName>
            </value>
            <value>
                <fullName>Rosy Red</fullName>
            </value>
            <value>
                <fullName>Spectacular Sunset</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/numberOfFlowers__c.field-meta.xml
<CustomField>
    <fullName>numberOfFlowers__c</fullName>
    <defaultValue>12</defaultValue>
    <label>Number of Flowers</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/percentOfOpening__c.field-meta.xml
<CustomField>
    <fullName>percentOfOpening__c</fullName>
    <description>How open are the flowers in the bouquet?</description>
    <inlineHelpText>How open are the flowers in the bouquet?</inlineHelpText>
    <label>Percent of Flower Opening</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/classes/OrderItemUtility.cls
public with sharing class OrderItemUtility {
    public OrderItemUtility() {}

    public static void addBonusBouquet(List<Order> ordersFromTrigger) {
        Product2 bonusProduct = new Product2();
        PricebookEntry entry = new PricebookEntry();
        List<OrderItem> newBouquets = new List<OrderItem>();
        List<Product2> bonusProductList = [SELECT Id, ProductCode FROM Product2 WHERE ProductCode = 'BOT-BB-12'];
        
        if(bonusProductList.size() > 0) {
            bonusProduct = bonusProductList[0];
            List<PricebookEntry> entryList = [
                SELECT Id, Product2Id 
                FROM PricebookEntry 
                WHERE Product2Id = :bonusProduct.Id
            ];

            if(entryList.size() > 0) {
                entry = entryList[0];
            }

            for(Order currentOrder : ordersFromTrigger) {
                if(currentOrder.Status == 'Activated') {
                    OrderItem freeBouquet = new OrderItem(
                        OrderId = currentOrder.id, 
                        PricebookEntryId = entry.id,
                        numberOfFlowers__c = 3,
                        description = 'FREE Bouquet',
                        Quantity = 1,
                        colorTheme__c = 'Spectacular Sunset',
                        percentOfOpening__c = 0,
                        UnitPrice = 0.00
                    );
                    newBouquets.add(freeBouquet);
                }
            }
            insert newBouquets;
        }
    }
}