force-app/main/default/objects/Cloud_News__e/Cloud_News__e.object-meta.xml
<CustomObject>
    <description>Os eventos da Cloud News trazem as notícias até as pontas de seus dedos</description>
    <label>Cloud News</label>
    <pluralLabel>Cloud News</pluralLabel>
</CustomObject>

force-app/main/default/objects/Cloud_News__e/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Local</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Cloud_News__e/fields/Urgent__c.field-meta.xml
<CustomField>
    <fullName>Urgent__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Urgente</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/CloudNewEvents.cls
public with sharing class CloudNewEvents {
    public void createNewEventMessage(){
        Cloud_News__e newsEvent = new Cloud_News__e(
                Location__c='Mountain City',
                Urgent__c=true,
                News_Content__c='Lake Road is closed due to mudslides.'
        );
        
        // Call method to publish events
        Database.SaveResult eventResult = EventBus.publish(newsEvent);

        if (eventResult.isSuccess()) {
            System.debug('Successfully published event.');
        } else {
            for(Database.Error err : eventResult.getErrors()) {
                System.debug('Error returned: ' +
                            err.getStatusCode() +
                            ' - ' +
                            err.getMessage()
                );
            }
        }
    }

    public void createNewEventsListMessage(){
        List<Cloud_News__e> newsEventList = new List<Cloud_News__e>();

        Cloud_News__e newsEvent1 = new Cloud_News__e(
                Location__c='Mountain City',
                Urgent__c=true,
                News_Content__c='Lake Road is closed due to mudslides.'
        );
        newsEventList.add(newsEvent1);

        Cloud_News__e newsEvent2 = new Cloud_News__e(
                Location__c='Mountain City',
                Urgent__c=false,
                News_Content__c='Small incident on Goat Lane causing traffic.'
        );
        newsEventList.add(newsEvent2);

        // Call method to publish events
        List<Database.SaveResult> results = EventBus.publish(newsEventList);
    
        for (Database.SaveResult eventResult : results) {
            if (eventResult.isSuccess()) {
                System.debug('Successfully published event.');
            } else {
                for(Database.Error err : eventResult.getErrors()) {
                    System.debug('Error returned: ' +
                                err.getStatusCode() +
                                ' - ' +
                                err.getMessage()
                    );
                }
            }
        } 
    }
}